# fly.toml app configuration file generated for ntuc-price-is-right on 2025-04-07T14:21:02+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ntuc-price-is-right'
primary_region = 'sin'
kill_signal = 'SIGTERM'

[build]

[env]
  DATABASE_PATH = '/mnt/name/database.db'
  PHX_HOST = 'ntuc-price-is-right.fly.dev'
  PORT = '8080'

[[mounts]]
  source = 'name'
  destination = '/mnt/name'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
